spring:
  application:
    name: Web-Java
server:
  port: 9090

application:
  rest-client:
    response-timeout: 1000
  price-advisor-service:
    base-path: http://localhost:8089
    advisor: ${application.price-advisor-service.base-path}/api/v1/price-comparison
  feature:
    toggles:
      cats-products: true

      kitty-products: false

      spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
